FROM java:8
ADD ${receiverCodeArtifactId}-${receiverCodeVersion}.jar /${receiverCodeArtifactId}.jar
EXPOSE $receiverServerPort
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/${receiverCodeArtifactId}.jar"]